In [3]:
import numpy as np
import pandas as pd

In [43]:
df=pd.read_csv(r"C:\Users\SAGAR\seaborn-data\iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

In [44]:
df['species'].value_counts()

versicolor    50
virginica     50
setosa        50
Name: species, dtype: int64

In [45]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [47]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [48]:
x=df.iloc[:,1:5]
y=df.iloc[:,-1]
x

sepal_width  petal_length  petal_width    species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
5            3.9           1.7          0.4     setosa
6            3.4           1.4          0.3     setosa
7            3.4           1.5          0.2     setosa
8            2.9           1.4          0.2     setosa
9            3.1           1.5          0.1     setosa
10           3.7           1.5          0.2     setosa
11           3.4           1.6          0.2     setosa
12           3.0           1.4          0.1     setosa
13           3.0           1.1          0.1     setosa
14           4.0           1.2          0.2     setosa
15           4.4           1.5          0.4     setosa
16           3.9           1.3          0.4     setosa
17           3.5           1.4          0.3     setosa
18           3.8           1.7          0.3     setosa
19           3.8           1.5          0.3     setosa
20           3.4           1.7          0.2     setosa
21           3.7           1.5          0.4     setosa
22           3.6           1.0          0.2     setosa
23           3.3           1.7          0.5     setosa
24           3.4           1.9          0.2     setosa
25           3.0           1.6          0.2     setosa
26           3.4           1.6          0.4     setosa
27           3.5           1.5          0.2     setosa
28           3.4           1.4          0.2     setosa
29           3.2           1.6          0.2     setosa
..           ...           ...          ...        ...
120          3.2           5.7          2.3  virginica
121          2.8           4.9          2.0  virginica
122          2.8           6.7          2.0  virginica
123          2.7           4.9          1.8  virginica
124          3.3           5.7          2.1  virginica
125          3.2           6.0          1.8  virginica
126          2.8           4.8          1.8  virginica
127          3.0           4.9          1.8  virginica
128          2.8           5.6          2.1  virginica
129          3.0           5.8          1.6  virginica
130          2.8           6.1          1.9  virginica
131          3.8           6.4          2.0  virginica
132          2.8           5.6          2.2  virginica
133          2.8           5.1          1.5  virginica
134          2.6           5.6          1.4  virginica
135          3.0           6.1          2.3  virginica
136          3.4           5.6          2.4  virginica
137          3.1           5.5          1.8  virginica
138          3.0           4.8          1.8  virginica
139          3.1           5.4          2.1  virginica
140          3.1           5.6          2.4  virginica
141          3.1           5.1          2.3  virginica
142          2.7           5.1          1.9  virginica
143          3.2           5.9          2.3  virginica
144          3.3           5.7          2.5  virginica
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [49]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
5         setosa
6         setosa
7         setosa
8         setosa
9         setosa
10        setosa
11        setosa
12        setosa
13        setosa
14        setosa
15        setosa
16        setosa
17        setosa
18        setosa
19        setosa
20        setosa
21        setosa
22        setosa
23        setosa
24        setosa
25        setosa
26        setosa
27        setosa
28        setosa
29        setosa
         ...    
120    virginica
121    virginica
122    virginica
123    virginica
124    virginica
125    virginica
126    virginica
127    virginica
128    virginica
129    virginica
130    virginica
131    virginica
132    virginica
133    virginica
134    virginica
135    virginica
136    virginica
137    virginica
138    virginica
139    virginica
140    virginica
141    virginica
142    virginica
143    virginica
144    virginica
145    virginica
146    virginica
147    virgini

In [50]:
type(x)

pandas.core.frame.DataFrame

In [52]:
x=df.iloc[:,1:4].values
y=df.iloc[:,-1].values
x

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.2],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.6, 1.4, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3

In [54]:
type(x)
type(y)

numpy.ndarray

In [61]:
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
y=lb.fit_transform(y)#in last column having species 3 value.1st is satosa,2nd species is versicloor,3rd is varginica.
y#1st column is create is for satosa 2nd column in result is for Varsicolor and last column create  is verginica.means categorical value convert into binary value(0 and 1 format)

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [78]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2,random_state=0)#x is independent valriable,and y is dependent variable.

In [79]:
x_train[:5,:]

array([[3.1, 5.5, 1.8],
       [3. , 4.5, 1.5],
       [3.5, 1.5, 0.2],
       [3. , 4.9, 1.8],
       [2.8, 5.6, 2.2]])

In [85]:
x_train

array([[3.1, 5.5, 1.8],
       [3. , 4.5, 1.5],
       [3.5, 1.5, 0.2],
       [3. , 4.9, 1.8],
       [2.8, 5.6, 2.2],
       [2.7, 3.9, 1.4],
       [3.8, 1.7, 0.3],
       [2.7, 5.1, 1.6],
       [3. , 4.2, 1.5],
       [2.6, 4. , 1.2],
       [3. , 5.5, 2.1],
       [3.2, 1.3, 0.2],
       [3.1, 5.1, 2.3],
       [3.5, 1.6, 0.6],
       [3.7, 1.5, 0.2],
       [2. , 3.5, 1. ],
       [3. , 5.5, 1.8],
       [3.3, 5.7, 2.5],
       [2.2, 5. , 1.5],
       [2.5, 5.8, 1.8],
       [2.5, 3.9, 1.1],
       [3. , 6.1, 2.3],
       [3.3, 4.7, 1.6],
       [2.4, 3.8, 1.1],
       [2.7, 4.9, 1.8],
       [2.8, 5.1, 1.5],
       [2.5, 4.5, 1.7],
       [2.5, 5. , 1.9],
       [3.2, 4.7, 1.4],
       [3. , 5.2, 2. ],
       [3.4, 4.5, 1.6],
       [3.1, 1.6, 0.2],
       [2.7, 5.1, 1.9],
       [2.7, 4.2, 1.3],
       [2.9, 3.6, 1.3],
       [2.5, 4. , 1.3],
       [3. , 4.6, 1.4],
       [3.2, 6. , 1.8],
       [3.7, 1.5, 0.2],
       [3. , 1.1, 0.1],
       [2.7, 5.3, 1.9],
       [3. , 4.2

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
clas=RandomForestClassifier(n_estimators=50)


In [89]:
clas.fit(x_train,y_train)

ValueError: Unknown label type: 'continuous-multioutput'

In [90]:
y_pred=classifier.predict(x_test)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [93]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred)

NameError: name 'y_pred' is not defined